module.exports = [
    {
        winery: "Kendall-Jackson",
        name: "Grand Reserve Chardonnay 2018",
        img: "https://www.wine.com/product/images/w_1024,h_3310,c_fit,q_auto:good,fl_progressive/d1pyuzrupojo0xnvhtv8.jpg",
        price: 20.99,
        quantity: 50,
        grapes: "Blend: 81% Cabernet Sauvignon, 12.6% Merlot, 3.6% Cabernet Franc, 2.4% Petit Verdot, 0.4% Malbec",
        description: "The 2015 Napa Valley Cabernet Sauvignon has a deep, rich red color with a purple rim. A robust wine with an assertive and alluring attack, it has notes of strawberry, cigar and tea leaves with a touch of black pepper and clove. A mouthwatering mid-palate of raspberry is followed by an expressive and bright finish. With lush and silky tannins, this ageworthy wine will show beautifully through 2038 given proper cellaring conditions.",
        region: "Santa Barbara, Central Coast",
        country: "California, US",
        ratings: 4.1,
        numberOfRatings: 184,
        type: "White Wine",
    },
    {
        winery: "San Filippo",
        name: "Brunello di Montalcino Le Lucere 2015",
        img: "https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/wzzll1qetxmhgt1gpquj.jpg.jpg",
        price: 94.99,
        quantity: 25,
        grapes: "Sangiovese",
        region: "Montalcino",
        description: "The color on the 2015 San Filippo Brunello di Montalcino Le Lucere is a ruby red with reflexes verging on garnet. The perfume is intense, fine and elegant, with notes of cherries preserved in alcohol, enriched with spices redolent of cinnamon and cloves. On the palate it explodes in all its fineness and elegance thanks to the dense and silky tannins. Excellent body that renders the flavor harmonious and persistent. Excellent nose-mouth correspondence.",
        country: "Tuscany, Italy",
        ratings: 4.3,
        numberOfRatings: 17,
        type: "Red Wine",
    },
    {
        winery: "Conti Costanti",
        name: "Brunello di Montalcino 2015",
        img: "https://www.https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/z73fpos2sohreagnttpm.jpg.com/product/images/w_1024,https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/z73fpos2sohreagnttpm.jpg,c_fit,q_auto:good,fl_progressive/ayeqaukkka59tq6wrovi.jpg",
        price: 109.99,
        quantity: 12,
        grapes: "Sangiovese",
        description: "Deep ruby red with brilliant garnet reflections, the bouquet is rich, ample and intense with notes of brushwood, berries, plums, violets, spices and vanilla confirmed on the palate; wonderful elegance and balance, lush concentration, voluptuous body and silky, smooth tannins. Shows power and finesse all at once. \nA wonderful accompaniment to red meat, stews, complex dishes and aged cheese.",
        region: "Montalcino",
        country: "Tuscany, Italy",
        ratings: 4.3,
        numberOfRatings: 7,
        type: "Red Wine",
    },
    {
        name: "Donnafugata Ben Rye (375ML half-bottle) 2017",
        winery: "Passito Di Pantelleria",
        region: "Donnafugata",
        ratings: "4.9",
        country: "Sicily, Italy",
        price: "45.99",
        quantity: "35",
        numberOfRatings: "25",
        type: "Red Wine",
        img: "https://www.https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/pvbrxmz5tfclro94xfvq.jpg.com/product/images/w_1920,h_4479,c_fit,q_auto:good,fl_progressive/zget94jyzhzh4hophjhz.jpg",
        grapes: "Zibibbo",
        description: "Ben Ryé 2017 offers an extraordinary rich bouquet with outstanding aromas obtained from the dried grapes: apricots and candied orange peel. The palate is very fresh and intense, balancing perfectly the sweetness followed by a long and satisfying persistence. It matches with caramelized duck, foie gras and blue cheeses. It goes well with pastries and gourmet chocolate like gianduja. Extraordinary alone, as a meditation wine.",
    },
]