module.exports = [
    {
        winery: "Silver Oak",
        name: "Cabernet Sauvignon 2015",
        img: "https://www.wine.com/product/images/w_1920,h_5416,c_fit,q_auto:good,fl_progressive/bvvjc1blvhs3e5x6w9q2.jpg",
        price: 124.99,
        quantity: 54,
        grapes: "Blend: 81% Cabernet Sauvignon, 12.6% Merlot, 3.6% Cabernet Franc, 2.4% Petit Verdot, 0.4% Malbec",
        description: "The 2015 Napa Valley Cabernet Sauvignon has a deep, rich red color with a purple rim. A robust wine with an assertive and alluring attack, it has notes of strawberry, cigar and tea leaves with a touch of black pepper and clove. A mouthwatering mid-palate of raspberry is followed by an expressive and bright finish. With lush and silky tannins, this ageworthy wine will show beautifully through 2038 given proper cellaring conditions.",
        region: "Napa Valley",
        country: "California, US",
        ratings: 3.8,
        numberOfRatings: 84,
        type: "Red Wine",
    },
    {
        winery: "Stags' Leap",
        name: "Cabernet Sauvignon 2017",
        img: "https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/e8d0jbppav6y5nf0wbfy.jpg",
        price: 49.99,
        quantity: 75,
        grapes: "Cabernet Sauvignon 100%",
        region: "Napa Valley",
        description: "Cabernet Sauvignon is aromatically beautiful, introducing itself with alluring notes of dark, red fruit and a peppery spice, The aromatics and oak are seamlessly integrated together in this juicy wine, showcasing the ideal amount of blueberry and blackberry flavors",
        country: "California, US",
        ratings: 4.1,
        numberOfRatings: 207,
        type: "Red Wine",
    },
    {
        winery: "Groth",
        name: "Cabernet Sauvignon 2015",
        img: "https://www.wine.com/product/images/w_1024,h_3243,c_fit,q_auto:good,fl_progressive/ayeqaukkka59tq6wrovi.jpg",
        price: 65,
        quantity: 42,
        grapes: "Cabernet sauvignon 100%",
        description: "The 2015 Cabernet Sauvignon is big and lush with huge gobs of fruit in the aroma and flavor. The texture of the wine is soft and supple, typical of Cabernet Sauvignons grown in our area of the Oakville AVA. The sweet vanilla character derived from 22 months in the barrels blends well with the black cherry and blackberry flavors and aromas of the wine.",
        region: "Oakville",
        country: "California, US",
        ratings: 3.9,
        numberOfRatings: 54,
        type: "Red Wine",
    },
    {
        name: "Cabernet Sauvignon 2017",
        winery: "Joseph Phelps",
        region: "Napa Valley",
        ratings: "4.1",
        country: "California, US",
        price: "75.99",
        quantity: "15",
        numberOfRatings: "12",
        type: "Red Wine",
        img: "https://www.wine.com/product/images/w_1920,h_4479,c_fit,q_auto:good,fl_progressive/zget94jyzhzh4hophjhz.jpg",
        grapes: "Blend: 92% Cabernet Sauvignon, 6% Malbec, 1% Petit Verdot and 1% Cabernet Franc",
        description: "The 2017 Cabernet Sauvignon has expressive aromatics of blueberry, boysenberry, baking spices and cardamom. A fresh and inviting wine with unfolding layers of raspberry, red cherry, nutmeg, cedar and graphite with a medium-full body, seamless integrated tannins and a lengthy finish.",
    },
]